language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'

env:
  - DJANGO_VERSION=1.4.3
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.10

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install Django==$DJANGO_VERSION

script: nosetests --with-coverage --nologcapture

after_success: coveralls

notifications:
  hipchat: 5534a6204d6caa1a45ac2444282aca@WebDevActivity
  email: false
