language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
script: coverage run membersuite-api-client/tests.py
after_success: coveralls
notifications:
  hipchat: 5534a6204d6caa1a45ac2444282aca@WebDevActivity
  email: false
